export const TECHNICAL_MANUALS: Record<string, string[]> = {
  terminal: [
    "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓",
    "┃  GLOBAL KERNEL SHELL v1.6 - ENTERPRISE EDITION       ┃",
    "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛",
    "",
    "[[BLUE]]SYSTEM ARCHITECTURE:[[RESET]]",
    "The kernel operates on a flat 10.0.0.0/24 logical plane.",
    "Hardware must be powered and identified before orchestration.",
    "",
    "[[YELLOW]]BOOTSTRAP WORKFLOW:[[RESET]]",
    "1. [[GREEN]]poweron[[RESET]]        - Initialize hardware state",
    "2. [[GREEN]]hostname [ID][[RESET]] - Assign unique system identity",
    "3. [[GREEN]]ip setup[[RESET]]     - Provision logical network stack",
    "",
    "[[BLUE]]PRO-TIPS:[[RESET]]",
    "• [[YELLOW]][Tab][[RESET]] - Context-aware autocomplete",
    "• [[YELLOW]]watch [cmd][[RESET]] - Real-time metric monitoring",
    "• [[YELLOW]]top[[RESET]] - Integrated resource scheduler view"
  ],
  dhcp: [
    "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓",
    "┃  PROTOCOL: DHCP ORCHESTRATION (v1.6)                 ┃",
    "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛",
    "",
    "[[BLUE]]OVERVIEW:[[RESET]]",
    "Automates IPv4 allocation across the 10.0.0.0/24 fabric.",
    "Required for 'Day 1' automated node provisioning.",
    "",
    "[[GREEN]]1. HARDWARE READINESS[[RESET]]",
    "• Deploy 1x Compute Node (Control Plane).",
    "• Use Patch Panel: Connect Node [Port 1] to Site Core Switch.",
    "",
    "[[GREEN]]2. SYSTEM INITIALIZATION[[RESET]]",
    "• Open Node Console: [[YELLOW]]poweron[[RESET]]",
    "• Set Identity: [[YELLOW]]hostname dhcp-srv-01[[RESET]]",
    "• Static IP (IPMI): [[YELLOW]]ipmi set-ip 10.0.0.10[[RESET]]",
    "",
    "[[GREEN]]3. SERVICE DEPLOYMENT[[RESET]]",
    "• [[YELLOW]]apt install isc-dhcp-server[[RESET]]",
    "• Edit [[YELLOW]]/etc/dhcp/dhcpd.conf[[RESET]] to define range.",
    "• [[YELLOW]]systemctl enable --now dhcp[[RESET]]",
    "",
    "[[GREEN]]4. VALIDATION PROBE[[RESET]]",
    "• Deploy a second node (Client).",
    "• Logical Patch the client to the same L2 network.",
    "• Client should automatically receive 10.0.0.x address."
  ],
  dns: [
    "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓",
    "┃  PROTOCOL: BIND9 DNS ORCHESTRATION                   ┃",
    "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛",
    "",
    "[[BLUE]]OVERVIEW:[[RESET]]",
    "Translates hostnames to IP addresses. Gates high-level",
    "service orchestration (DB clusters, Web farms).",
    "",
    "[[GREEN]]1. PREREQUISITES[[RESET]]",
    "• Dedicated Compute Node with high availability.",
    "• Active DHCP service (recommended for static assignments).",
    "",
    "[[GREEN]]2. BOOTSTRAP PHASE[[RESET]]",
    "• [[YELLOW]]poweron[[RESET]] -> [[YELLOW]]hostname dns-auth-01[[RESET]]",
    "• Assignment: [[YELLOW]]ip setup 10.0.0.53 10.0.0.1[[RESET]]",
    "",
    "[[GREEN]]3. CONFIGURATION[[RESET]]",
    "• [[YELLOW]]apt install bind9[[RESET]]",
    "• Use the 'Services Dashboard' -> 'Configure' UI to",
    "  inject A-Records into the authoritative zone.",
    "",
    "[[GREEN]]4. TESTING[[RESET]]",
    "• From any node: [[YELLOW]]ping [custom-hostname][[RESET]]",
    "• ICMP echo should resolve to the mapped IP."
  ],
  ntp: [
    "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓",
    "┃  PROTOCOL: NTP TIME SYNCHRONIZATION                 ┃",
    "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛",
    "",
    "[[BLUE]]OVERVIEW:[[RESET]]",
    "Ensures log consistency and transaction atomicity across",
    "distributed nodes using Stratum-2 timing.",
    "",
    "[[GREEN]]1. DEPLOYMENT[[RESET]]",
    "• Provision 1x Node as Master Clock.",
    "• [[YELLOW]]apt install ntp[[RESET]]",
    "• [[YELLOW]]systemctl start ntp[[RESET]]",
    "",
    "[[GREEN]]2. FLEET INTEGRATION[[RESET]]",
    "• All nodes must be logical patched to the clock node.",
    "• Nodes will automatically sync heartbeat upon boot.",
    "",
    "[[GREEN]]3. METRICS[[RESET]]",
    "• View 'Time-Sync Status' in Dashboard.",
    "• Aim for < 0.05ms jitter for database workloads."
  ],
  bootstrap: [
    "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓",
    "┃  PROTOCOL: BOOTSTRAP WORKFLOW (v1.6)                 ┃",
    "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛",
    "",
    "[[BLUE]]DAY 1 PROVISIONING STEPS:[[RESET]]",
    "",
    "1. [[GREEN]]scan console[[RESET]]",
    "   Discover unconfigured hardware on the local management plane.",
    "",
    "2. [[GREEN]]connect console [ID][[RESET]]",
    "   Establish a serial OOB link to the target node's kernel.",
    "",
    "3. [[GREEN]]poweron[[RESET]]",
    "   Initialize system resources (CPU, RAM, POST sequence).",
    "",
    "4. [[GREEN]]hostname [NAME][[RESET]]",
    "   Assign a unique identity. This gates all network services.",
    "",
    "5. [[GREEN]]ip setup [IP] [GW] [DNS][[RESET]]",
    "   Provision the logical networking stack for 10.0.0.0/24.",
    "",
    "6. [[GREEN]]exit[[RESET]]",
    "   Detach console. The node is now ready for SSH/Orchestration."
  ],
  services: [
    "--- ENTERPRISE SERVICE ORCHESTRATION ---",
    "Select a specific orchestrator from the grid to access",
    "deep-dive technical manuals and configuration tables."
  ]
};
