import type { InfraNode } from '../../store/infraTypes'
import { type NetworkDemand, INCIDENT_PROFILES } from './types'

/**
 * calculateNodeDemand
 * Determines the baseline network traffic generated by a server and scales it based on
 * incident profile modifiers (like ransomware DDoS spike or operational degradation drop).
 */
export function calculateNodeDemand(node: InfraNode, networkLoad: number): NetworkDemand {
  // If node is blackholed, all traffic demands drop to zero immediately
  if (node.isBlackholed) {
    return { nodeId: node.id, demandGbps: 0, activeIncident: 'blackholed' }
  }

  if (node.type === 'rack' || node.type === 'cooling') {
    return { nodeId: node.id, demandGbps: 0 }
  }

  // Base demand depending on server type
  let baseDemand = 0
  if (node.type === 'compute') {
    baseDemand = 0.8 * (1 + networkLoad)
  } else if (node.type === 'storage') {
    baseDemand = 1.5 * (1 + networkLoad)
  } else if (node.type === 'backup') {
    baseDemand = 1.0 * (1 + networkLoad)
  } else if (node.type === 'security' || node.type === 'load_balancer') {
    baseDemand = 0.5 * (1 + networkLoad)
  } else if (node.type === 'identity') {
    baseDemand = 0.2 * (1 + networkLoad)
  } else if (node.type === 'network') {
    baseDemand = 0.1 // Baseline switches management frame
  }

  let activeIncident: string | undefined
  let multiplier = 1.0

  // Apply incident modifier profile
  if (node.infectionState && node.infectionState !== 'clean') {
    activeIncident = 'ransomware'
    multiplier = INCIDENT_PROFILES.ransomware!.trafficMultiplier
  } else if (node.healthStatus === 'critical' || node.degradation > 80) {
    activeIncident = 'degraded'
    multiplier = INCIDENT_PROFILES.degraded!.trafficMultiplier
  }

  let demandGbps = baseDemand * multiplier

  // Apply administrative rate limit ceiling if active
  if (node.rateLimitGbps !== undefined && node.rateLimitGbps >= 0) {
    demandGbps = Math.min(demandGbps, node.rateLimitGbps)
  }

  return {
    nodeId: node.id,
    demandGbps,
    activeIncident
  }
}
